import {
  Color,
  type StandardMaterial,
  type Texture,
  Vec2,
  ANIM_GREATER_THAN,
  ANIM_LESS_THAN,
  BLEND_NONE,
  DITHER_NONE,
} from 'playcanvas';
import { PreloadTextures } from '~/lib/playcanvas/assets/ultra-boy/texture';
import { AnimationName } from '~/lib/playcanvas/assets/ultra-boy/animation';

export const AnimStateGraphData = {
  layers: [
    {
      name: 'Base',
      states: [
        {
          name: 'START',
        },
        {
          name: 'ANY',
        },
        {
          name: 'END',
        },
        {
          name: AnimationName.Idle,
          speed: 1.0,
          loop: true,
          defaultState: true,
        },
        {
          name: AnimationName.Talking,
          speed: 1.0,
          loop: true,
        },
        {
          name: AnimationName.Dance,
          speed: 1.0,
          loop: true,
        },
      ],
      transitions: [
        {
          from: 'START',
          to: AnimationName.Idle,
          defaultTransition: true,
        },
        {
          from: 'ANY',
          to: AnimationName.Idle,
          time: 0.15,
          conditions: [
            {
              value: 0,
              predicate: ANIM_GREATER_THAN,
              parameterName: 'xDirection',
            },
            {
              value: 0,
              predicate: ANIM_GREATER_THAN,
              parameterName: 'zDirection',
            },
          ],
        },
        {
          from: 'ANY',
          to: AnimationName.Talking,
          time: 0.15,
          conditions: [
            {
              value: 0,
              predicate: ANIM_GREATER_THAN,
              parameterName: 'xDirection',
            },
            {
              value: 0,
              predicate: ANIM_LESS_THAN,
              parameterName: 'zDirection',
            },
          ],
        },
        {
          from: 'ANY',
          to: AnimationName.Dance,
          time: 0.15,
          conditions: [
            {
              value: 0,
              predicate: ANIM_LESS_THAN,
              parameterName: 'xDirection',
            },
            {
              value: 0,
              predicate: ANIM_LESS_THAN,
              parameterName: 'zDirection',
            },
          ],
        },
        {
          from: 'ANY',
          to: AnimationName.Walk,
          time: 0.15,
          conditions: [
            {
              value: 0,
              predicate: ANIM_LESS_THAN,
              parameterName: 'xDirection',
            },
            {
              value: 0,
              predicate: ANIM_GREATER_THAN,
              parameterName: 'zDirection',
            },
          ],
        },
      ],
    },
  ],
  parameters: {
    xDirection: {
      name: 'xDirection',
      type: 'FLOAT',
      value: 0.5,
    },
    zDirection: {
      name: 'zDirection',
      type: 'FLOAT',
      value: 0.5,
    },
  },
};

export const CiberBoyMaterialConfig: Partial<StandardMaterial> = {
  aoMap: PreloadTextures.TextureAmbient.resource as Texture,
  aoMapUv: 0,
  aoMapChannel: 'r',
  occludeSpecular: 1.0,
  aoIntensity: 1.0,
  ambient: new Color().fromString('#ffffff'),

  diffuseMap: PreloadTextures.TextureDiffuse.resource as Texture,
  diffuseMapUv: 0,
  diffuseMapChannel: 'rgb',
  diffuseVertexColor: false,
  diffuse: new Color().fromString('#ffffff'),

  useMetalness: true,
  metalnessMap: PreloadTextures.TextureAmbient.resource as Texture,
  metalnessMapUv: 0,
  metalnessMapChannel: 'b',
  metalnessVertexColor: false,
  metalness: 1.0,
  useMetalnessSpecularColor: true,
  specular: new Color().fromString('#ffffff'),
  specularityFactor: 0.258,

  glossMap: PreloadTextures.TextureAmbient.resource as Texture,
  glossMapUv: 0,
  glossMapChannel: 'g',
  glossVertexColor: false,
  gloss: 2, // shininess: 100,
  glossInvert: true,

  emissiveMap: PreloadTextures.TextureEmissive.resource as Texture,
  emissiveMapUv: 0,
  emissiveMapChannel: 'rgb',
  emissiveVertexColor: false,
  emissive: new Color().fromString('#ffffff'),
  emissiveIntensity: 7.46,

  blendType: BLEND_NONE,
  opacityMap: PreloadTextures.TextureDiffuse.resource as Texture,
  opacityMapUv: 0,
  opacityMapChannel: 'a',
  opacityVertexColor: false,
  alphaTest: 0,
  alphaToCoverage: false,
  opacityDither: DITHER_NONE,
  opacityShadowDither: DITHER_NONE,

  normalMap: PreloadTextures.TextureNormalMap.resource as Texture,
  normalMapUv: 0,
  bumpiness: 1.0,

  useSheen: false,
  cull: 1,
  useLighting: true,
  twoSidedLighting: false,
  depthWrite: true,
  clearCoatGlossInvert: false,
  specularTint: false,
  opacity: 1,
  reflectivity: 1,
  clearCoat: 0,
  clearCoatGloss: 1,
  clearCoatBumpiness: 1,
  refractionIndex: 0.666667,
  refraction: 0,
  aoMapTiling: new Vec2(1, 1),
  aoMapOffset: new Vec2(),
  aoMapRotation: 0,
  diffuseMapTiling: new Vec2(1, 1),
  diffuseMapOffset: new Vec2(),
  diffuseMapRotation: 0,
  specularMapChannel: 'rgb',
  specularMapUv: 0,
  specularMapTiling: new Vec2(1, 1),
  specularMapOffset: new Vec2(),
  specularMapRotation: 0,
  specularityFactorMap: null,
  specularityFactorMapChannel: 'r',
  specularityFactorMapUv: 0,
  specularityFactorMapTiling: new Vec2(1, 1),
  specularityFactorMapOffset: new Vec2(),
  specularityFactorMapRotation: 0,
  enableGGXSpecular: false,
  anisotropy: 0,
  metalnessMapTiling: new Vec2(1, 1),
  metalnessMapOffset: new Vec2(),
  metalnessMapRotation: 0,
  glossMapTiling: new Vec2(1, 1),
  glossMapOffset: new Vec2(),
  glossMapRotation: 0,
  clearCoatMapChannel: 'r',
  clearCoatMapUv: 0,
  clearCoatMapTiling: new Vec2(1, 1),
  clearCoatMapOffset: new Vec2(),
  clearCoatMapRotation: 0,
  clearCoatVertexColor: false,
  clearCoatVertexColorChannel: 'r',
  clearCoatGlossMapChannel: 'r',
  clearCoatGlossMapUv: 0,
  clearCoatGlossMapTiling: new Vec2(1, 1),
  clearCoatGlossMapOffset: new Vec2(),
  clearCoatGlossMapRotation: 0,
  clearCoatGlossVertexColor: false,
  clearCoatGlossVertexColorChannel: 'r',
  clearCoatNormalMapUv: 0,
  clearCoatNormalMapTiling: new Vec2(1, 1),
  clearCoatNormalMapOffset: new Vec2(),
  clearCoatNormalMapRotation: 0,
  sheenMap: null,
  sheenMapChannel: 'rgb',
  sheenMapUv: 0,
  sheenMapTiling: new Vec2(1, 1),
  sheenMapOffset: new Vec2(),
  sheenMapRotation: 0,
  emissiveMapTiling: new Vec2(1, 1),
  emissiveMapOffset: new Vec2(),
  emissiveMapRotation: 0,
  normalMapTiling: new Vec2(1, 1),
  normalMapOffset: new Vec2(),
  normalMapRotation: 0,
  dispersion: 0,
  heightMapChannel: 'r',
  heightMapUv: 0,
  heightMapTiling: new Vec2(1, 1),
  heightMapOffset: new Vec2(),
  heightMapRotation: 0,
  heightMapFactor: 1,
  alphaFade: true,
  opacityMapTiling: new Vec2(1, 1),
  opacityMapOffset: new Vec2(),
  opacityMapRotation: 0,
  opacityFadesSpecular: true,
  cubeMapProjection: 0,
  lightMapChannel: 'rgb',
  lightMapUv: 0,
  lightMapTiling: new Vec2(1, 1),
  lightMapOffset: new Vec2(),
  lightMapRotation: 0,
  depthTest: true,
  useFog: true,
  useSkybox: true,
  useTonemap: true,

  // sheenGlossInvert: false,
  // useDynamicRefraction: false,
  // useIridescence: false,
  // shininess: 100,
  // bumpMapFactor: 1,
  // sheenGloss: 0,
  // thickness: 0,
  // attenuationDistance: 0,
  // iridescence: 0,
  // iridescenceRefractionIndex: 0.666667,
  // iridescenceThicknessMin: 0,
  // iridescenceThicknessMax: 0,
  // ambientTint: true,
  // diffuseTint: true,
  // emissiveTint: true,
  // metalnessTint: true,
  // sheenTint: true,
  // sheenGlossTint: true,
  // attenuation: new Color().fromString('#ffffff'),
  // specularAntialias: true,
  // conserveEnergy: true,
  // sheenGlossMap: null,
  // sheenGlossMapChannel: 'r',
  // sheenGlossMapUv: 0,
  // sheenGlossMapTiling: new Vec2(1, 1),
  // sheenGlossMapOffset: new Vec2(),
  // sheenGlossMapRotation: 0,
  // refractionMap: null,
  // refractionMapChannel: 'r',
  // refractionMapUv: 0,
  // refractionMapTiling: new Vec2(1, 1),
  // refractionMapOffset: new Vec2(),
  // refractionMapRotation: 0,
  // refractionVertexColor: false,
  // refractionVertexColorChannel: 'r',
  // thicknessMap: null,
  // thicknessMapChannel: 'r',
  // thicknessMapUv: 0,
  // thicknessMapTiling: new Vec2(1, 1),
  // thicknessMapOffset: new Vec2(),
  // thicknessMapRotation: 0,
  // thicknessVertexColor: false,
  // thicknessVertexColorChannel: 'r',
  // iridescenceMap: null,
  // iridescenceMapChannel: 'r',
  // iridescenceMapUv: 0,
  // iridescenceMapTiling: new Vec2(1, 1),
  // iridescenceMapOffset: new Vec2(),
  // iridescenceMapRotation: 0,
  // iridescenceThicknessMap: null,
  // iridescenceThicknessMapChannel: 'r',
  // iridescenceThicknessMapUv: 0,
  // iridescenceThicknessMapTiling: new Vec2(1, 1),
  // iridescenceThicknessMapOffset: new Vec2(),
  // iridescenceThicknessMapRotation: 0,
  // useGammaTonemap: true,
  // mapping_format: 'path',
};
